#!/bin/bash

clear

MAIN="main.c"
FILENAME="main"

DFLAGS="-Wall -Wno-psabi -Wfatal-errors -Wno-unused-function"
LFLAGS="-ljansson -lcurl"

echo "Cleaning up..."
rm *.o

if [ "$1" == "debug" ] || [ "$1" == "d" ]; then

    echo "Compiling in debugmode"

	gcc -g -c -D COMPILEDEBUG $MAIN $LFLAGS $DFLAGS || exit

else  

	if [ "$1" == "gdb" ]; then
		echo "Compiling for gdb"

		gcc -g -D COMPILEDEBUG -c $MAIN -luuid -pthread -lbsd $LFLAGS $DFLAGS || exit

	else
	    echo "Compiling"

		gcc -c $MAIN -luuid -lcurl -pthread -lbsd $LFLAGS $DFLAGS || exit
	fi
fi

echo "Removing old application..."
rm bin/$FILENAME
echo "Linking..."

gcc -Wall -o bin/$FILENAME main.o $LFLAGS || exit

echo "Setting chmod..."
chmod +x bin/$FILENAME

echo "Cleaning up..."
rm *.o

echo "All done!"
echo "File: bin/\"$FILENAME\" is created"

if [ "$1" == "r" ] || [ "$1" == "R" ] || [ "$2" == "r" ] || [ "$2" == "R" ]; then
	./bin/$FILENAME
fi
